import { references } from '../content/references'
import { ReferenceList } from '../components/ReferenceList'

export function AboutView() {
  const allIds = Object.keys(references)
  return (
    <div className="max-w-3xl mx-auto p-5 space-y-5">
      <header>
        <h1 className="text-xl font-bold text-slate-100">About VentTeach</h1>
        <p className="text-sm text-slate-400 mt-1">
          An interactive teaching tool for basic ventilator settings and patient–ventilator
          dyssynchrony, designed for medical students, nurses, and residents.
        </p>
      </header>

      <section className="rounded-xl bg-rose-500/10 ring-1 ring-rose-500/30 p-4">
        <h2 className="text-sm font-semibold text-rose-100 mb-1">⚠️ Educational use only</h2>
        <p className="text-sm text-rose-100/90 leading-relaxed">
          The waveforms are generated by a simplified single-compartment lung model for teaching. It
          reproduces the qualitative behaviour of real ventilator tracings but is not a validated
          clinical device and must not be used for patient care decisions.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold text-sky-300">How it works</h2>
        <p className="text-sm text-slate-300 leading-relaxed">
          Every breath is computed in real time from the respiratory equation of motion, with
          adjustable compliance, resistance, and patient effort (Pmus). Because the physics is
          explicit, dyssynchronies are not drawn in by hand — they emerge from timing mismatches
          between the patient and the ventilator, exactly as they do at the bedside. That means you
          can not only see each asynchrony but change a setting and watch it resolve.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-sm font-semibold text-sky-300">How to teach with it</h2>
        <ul className="space-y-1.5">
          {[
            'Learn — work through the six fundamentals; each has a "Try this" button that loads a scenario into the live waveforms.',
            'Sandbox — free play with every setting; ideal for demonstrating a concept live in a lecture or on rounds.',
            'Dyssynchrony — six annotated asynchronies with mechanism, recognition, and fixes you can apply live.',
            'Challenges — learners identify the asynchrony and then resolve it; the app checks their fix.',
            'Use the Learner toggle (Student / Nurse / Resident) to flag stretch material and pitch depth appropriately.',
          ].map((x, i) => (
            <li key={i} className="flex gap-2 text-sm text-slate-300">
              <span className="text-sky-500 mt-0.5">▸</span>
              <span className="leading-snug">{x}</span>
            </li>
          ))}
        </ul>
        <p className="text-xs text-slate-500 leading-relaxed pt-1">
          The design follows evidence for simulation-based ventilation education and flipped-classroom
          ICU teaching, and manages cognitive load by revealing controls progressively rather than all
          at once (see references below).
        </p>
      </section>

      <ReferenceList ids={allIds} title="Full reference library (from Zotero)" />

      <footer className="text-xs text-slate-600 pt-2">
        Built as an open teaching resource. References curated from the educator’s Zotero library.
      </footer>
    </div>
  )
}
